{
    'name': 'Account Journal Entries Print',
    'sequence': 1,
    'author' : 'MAISOLUTIONSLLC',
    'email': 'apps@maisolutionsllc.com',
    'website':'http://maisolutionsllc.com/',
    'summary': 'Using this module you can print account journal entries',
    'description': """Using this module you can print account journal entries""",
    'category': 'Accounting',
    'version':'13.0.0.0',
    'license': 'AGPL-3',
    'depends' : ['account'],
    'data': [
        'report/account_view.xml',
    ],
    'qweb': [],
    'test': [],
    'installable': True,
    'application': False,
    'auto_install': False,
    'images': ['static/description/main_screenshot.png'],
}
